### ISSUE TITLE
I'm new to GitHub. I don't understand how to install this. Please give instructions in the README

### ISSUE THREAD

**Issue by Eden1914** [ItsFebiven/Elite_Mossy_Menu_Remake-BO3#1]
I'm clueless bro. Come on man, what the heck, I'm dumb

**Comment by ItsFebiven** [comment]
There is a tutorial online on how to use serious T7 compiler and if you don't want to use that then use infinity loader, I do not provide a tutorial myself as you need a compiler to inject this, Closed.
